//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace OAModel
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class OAEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“OAEntities”部分中的连接字符串初始化新 OAEntities 对象。
        /// </summary>
        public OAEntities() : base("name=OAEntities", "OAEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 OAEntities 对象。
        /// </summary>
        public OAEntities(string connectionString) : base(connectionString, "OAEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 OAEntities 对象。
        /// </summary>
        public OAEntities(EntityConnection connection) : base(connection, "OAEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<OA_Notice> OA_Notice
        {
            get
            {
                if ((_OA_Notice == null))
                {
                    _OA_Notice = base.CreateObjectSet<OA_Notice>("OA_Notice");
                }
                return _OA_Notice;
            }
        }
        private ObjectSet<OA_Notice> _OA_Notice;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<OA_NoticeAnnex> OA_NoticeAnnex
        {
            get
            {
                if ((_OA_NoticeAnnex == null))
                {
                    _OA_NoticeAnnex = base.CreateObjectSet<OA_NoticeAnnex>("OA_NoticeAnnex");
                }
                return _OA_NoticeAnnex;
            }
        }
        private ObjectSet<OA_NoticeAnnex> _OA_NoticeAnnex;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<OA_OfficeFile> OA_OfficeFile
        {
            get
            {
                if ((_OA_OfficeFile == null))
                {
                    _OA_OfficeFile = base.CreateObjectSet<OA_OfficeFile>("OA_OfficeFile");
                }
                return _OA_OfficeFile;
            }
        }
        private ObjectSet<OA_OfficeFile> _OA_OfficeFile;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<SS_OfficeFileType> SS_OfficeFileType
        {
            get
            {
                if ((_SS_OfficeFileType == null))
                {
                    _SS_OfficeFileType = base.CreateObjectSet<SS_OfficeFileType>("SS_OfficeFileType");
                }
                return _SS_OfficeFileType;
            }
        }
        private ObjectSet<SS_OfficeFileType> _SS_OfficeFileType;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<OA_FileTemp> OA_FileTemp
        {
            get
            {
                if ((_OA_FileTemp == null))
                {
                    _OA_FileTemp = base.CreateObjectSet<OA_FileTemp>("OA_FileTemp");
                }
                return _OA_FileTemp;
            }
        }
        private ObjectSet<OA_FileTemp> _OA_FileTemp;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<SS_OfficeFileTypeView> SS_OfficeFileTypeView
        {
            get
            {
                if ((_SS_OfficeFileTypeView == null))
                {
                    _SS_OfficeFileTypeView = base.CreateObjectSet<SS_OfficeFileTypeView>("SS_OfficeFileTypeView");
                }
                return _SS_OfficeFileTypeView;
            }
        }
        private ObjectSet<SS_OfficeFileTypeView> _SS_OfficeFileTypeView;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 OA_Notice EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToOA_Notice(OA_Notice oA_Notice)
        {
            base.AddObject("OA_Notice", oA_Notice);
        }
    
        /// <summary>
        /// 用于向 OA_NoticeAnnex EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToOA_NoticeAnnex(OA_NoticeAnnex oA_NoticeAnnex)
        {
            base.AddObject("OA_NoticeAnnex", oA_NoticeAnnex);
        }
    
        /// <summary>
        /// 用于向 OA_OfficeFile EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToOA_OfficeFile(OA_OfficeFile oA_OfficeFile)
        {
            base.AddObject("OA_OfficeFile", oA_OfficeFile);
        }
    
        /// <summary>
        /// 用于向 SS_OfficeFileType EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSS_OfficeFileType(SS_OfficeFileType sS_OfficeFileType)
        {
            base.AddObject("SS_OfficeFileType", sS_OfficeFileType);
        }
    
        /// <summary>
        /// 用于向 OA_FileTemp EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToOA_FileTemp(OA_FileTemp oA_FileTemp)
        {
            base.AddObject("OA_FileTemp", oA_FileTemp);
        }
    
        /// <summary>
        /// 用于向 SS_OfficeFileTypeView EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSS_OfficeFileTypeView(SS_OfficeFileTypeView sS_OfficeFileTypeView)
        {
            base.AddObject("SS_OfficeFileTypeView", sS_OfficeFileTypeView);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OAModel", Name="OA_FileTemp")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OA_FileTemp : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 OA_FileTemp 对象。
        /// </summary>
        /// <param name="gUID">GUID 属性的初始值。</param>
        public static OA_FileTemp CreateOA_FileTemp(global::System.Guid gUID)
        {
            OA_FileTemp oA_FileTemp = new OA_FileTemp();
            oA_FileTemp.GUID = gUID;
            return oA_FileTemp;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid GUID
        {
            get
            {
                return _GUID;
            }
            set
            {
                if (_GUID != value)
                {
                    OnGUIDChanging(value);
                    ReportPropertyChanging("GUID");
                    _GUID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GUID");
                    OnGUIDChanged();
                }
            }
        }
        private global::System.Guid _GUID;
        partial void OnGUIDChanging(global::System.Guid value);
        partial void OnGUIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FileName
        {
            get
            {
                return _FileName;
            }
            set
            {
                OnFileNameChanging(value);
                ReportPropertyChanging("FileName");
                _FileName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FileName");
                OnFileNameChanged();
            }
        }
        private global::System.String _FileName;
        partial void OnFileNameChanging(global::System.String value);
        partial void OnFileNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] FileBody
        {
            get
            {
                return StructuralObject.GetValidValue(_FileBody);
            }
            set
            {
                OnFileBodyChanging(value);
                ReportPropertyChanging("FileBody");
                _FileBody = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FileBody");
                OnFileBodyChanged();
            }
        }
        private global::System.Byte[] _FileBody;
        partial void OnFileBodyChanging(global::System.Byte[] value);
        partial void OnFileBodyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OrderNum
        {
            get
            {
                return _OrderNum;
            }
            set
            {
                OnOrderNumChanging(value);
                ReportPropertyChanging("OrderNum");
                _OrderNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderNum");
                OnOrderNumChanged();
            }
        }
        private Nullable<global::System.Int32> _OrderNum;
        partial void OnOrderNumChanging(Nullable<global::System.Int32> value);
        partial void OnOrderNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Visible
        {
            get
            {
                return _Visible;
            }
            set
            {
                OnVisibleChanging(value);
                ReportPropertyChanging("Visible");
                _Visible = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Visible");
                OnVisibleChanged();
            }
        }
        private Nullable<global::System.Boolean> _Visible;
        partial void OnVisibleChanging(Nullable<global::System.Boolean> value);
        partial void OnVisibleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> GUID_OfficeFileType
        {
            get
            {
                return _GUID_OfficeFileType;
            }
            set
            {
                OnGUID_OfficeFileTypeChanging(value);
                ReportPropertyChanging("GUID_OfficeFileType");
                _GUID_OfficeFileType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GUID_OfficeFileType");
                OnGUID_OfficeFileTypeChanged();
            }
        }
        private Nullable<global::System.Guid> _GUID_OfficeFileType;
        partial void OnGUID_OfficeFileTypeChanging(Nullable<global::System.Guid> value);
        partial void OnGUID_OfficeFileTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FileKey
        {
            get
            {
                return _FileKey;
            }
            set
            {
                OnFileKeyChanging(value);
                ReportPropertyChanging("FileKey");
                _FileKey = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FileKey");
                OnFileKeyChanged();
            }
        }
        private global::System.String _FileKey;
        partial void OnFileKeyChanging(global::System.String value);
        partial void OnFileKeyChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OAModel", Name="OA_Notice")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OA_Notice : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 OA_Notice 对象。
        /// </summary>
        /// <param name="gUID">GUID 属性的初始值。</param>
        /// <param name="orderNum">OrderNum 属性的初始值。</param>
        public static OA_Notice CreateOA_Notice(global::System.Guid gUID, global::System.Int32 orderNum)
        {
            OA_Notice oA_Notice = new OA_Notice();
            oA_Notice.GUID = gUID;
            oA_Notice.OrderNum = orderNum;
            return oA_Notice;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid GUID
        {
            get
            {
                return _GUID;
            }
            set
            {
                if (_GUID != value)
                {
                    OnGUIDChanging(value);
                    ReportPropertyChanging("GUID");
                    _GUID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GUID");
                    OnGUIDChanged();
                }
            }
        }
        private global::System.Guid _GUID;
        partial void OnGUIDChanging(global::System.Guid value);
        partial void OnGUIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderNum
        {
            get
            {
                return _OrderNum;
            }
            set
            {
                OnOrderNumChanging(value);
                ReportPropertyChanging("OrderNum");
                _OrderNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderNum");
                OnOrderNumChanged();
            }
        }
        private global::System.Int32 _OrderNum;
        partial void OnOrderNumChanging(global::System.Int32 value);
        partial void OnOrderNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NoticeDate
        {
            get
            {
                return _NoticeDate;
            }
            set
            {
                OnNoticeDateChanging(value);
                ReportPropertyChanging("NoticeDate");
                _NoticeDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NoticeDate");
                OnNoticeDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _NoticeDate;
        partial void OnNoticeDateChanging(Nullable<global::System.DateTime> value);
        partial void OnNoticeDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Notice
        {
            get
            {
                return _Notice;
            }
            set
            {
                OnNoticeChanging(value);
                ReportPropertyChanging("Notice");
                _Notice = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Notice");
                OnNoticeChanged();
            }
        }
        private global::System.String _Notice;
        partial void OnNoticeChanging(global::System.String value);
        partial void OnNoticeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> overdue
        {
            get
            {
                return _overdue;
            }
            set
            {
                OnoverdueChanging(value);
                ReportPropertyChanging("overdue");
                _overdue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("overdue");
                OnoverdueChanged();
            }
        }
        private Nullable<global::System.Boolean> _overdue;
        partial void OnoverdueChanging(Nullable<global::System.Boolean> value);
        partial void OnoverdueChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                OnEndDateChanging(value);
                ReportPropertyChanging("EndDate");
                _EndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndDate");
                OnEndDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndDate;
        partial void OnEndDateChanging(Nullable<global::System.DateTime> value);
        partial void OnEndDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> isPop
        {
            get
            {
                return _isPop;
            }
            set
            {
                OnisPopChanging(value);
                ReportPropertyChanging("isPop");
                _isPop = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isPop");
                OnisPopChanged();
            }
        }
        private Nullable<global::System.Boolean> _isPop;
        partial void OnisPopChanging(Nullable<global::System.Boolean> value);
        partial void OnisPopChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OAModel", Name="OA_NoticeAnnex")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OA_NoticeAnnex : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 OA_NoticeAnnex 对象。
        /// </summary>
        /// <param name="gUID">GUID 属性的初始值。</param>
        public static OA_NoticeAnnex CreateOA_NoticeAnnex(global::System.Guid gUID)
        {
            OA_NoticeAnnex oA_NoticeAnnex = new OA_NoticeAnnex();
            oA_NoticeAnnex.GUID = gUID;
            return oA_NoticeAnnex;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid GUID
        {
            get
            {
                return _GUID;
            }
            set
            {
                if (_GUID != value)
                {
                    OnGUIDChanging(value);
                    ReportPropertyChanging("GUID");
                    _GUID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GUID");
                    OnGUIDChanged();
                }
            }
        }
        private global::System.Guid _GUID;
        partial void OnGUIDChanging(global::System.Guid value);
        partial void OnGUIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> GUID_Notice
        {
            get
            {
                return _GUID_Notice;
            }
            set
            {
                OnGUID_NoticeChanging(value);
                ReportPropertyChanging("GUID_Notice");
                _GUID_Notice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GUID_Notice");
                OnGUID_NoticeChanged();
            }
        }
        private Nullable<global::System.Guid> _GUID_Notice;
        partial void OnGUID_NoticeChanging(Nullable<global::System.Guid> value);
        partial void OnGUID_NoticeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Annex
        {
            get
            {
                return StructuralObject.GetValidValue(_Annex);
            }
            set
            {
                OnAnnexChanging(value);
                ReportPropertyChanging("Annex");
                _Annex = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Annex");
                OnAnnexChanged();
            }
        }
        private global::System.Byte[] _Annex;
        partial void OnAnnexChanging(global::System.Byte[] value);
        partial void OnAnnexChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AnnexName
        {
            get
            {
                return _AnnexName;
            }
            set
            {
                OnAnnexNameChanging(value);
                ReportPropertyChanging("AnnexName");
                _AnnexName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AnnexName");
                OnAnnexNameChanged();
            }
        }
        private global::System.String _AnnexName;
        partial void OnAnnexNameChanging(global::System.String value);
        partial void OnAnnexNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OAModel", Name="OA_OfficeFile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OA_OfficeFile : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 OA_OfficeFile 对象。
        /// </summary>
        /// <param name="gUID">GUID 属性的初始值。</param>
        public static OA_OfficeFile CreateOA_OfficeFile(global::System.Guid gUID)
        {
            OA_OfficeFile oA_OfficeFile = new OA_OfficeFile();
            oA_OfficeFile.GUID = gUID;
            return oA_OfficeFile;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid GUID
        {
            get
            {
                return _GUID;
            }
            set
            {
                if (_GUID != value)
                {
                    OnGUIDChanging(value);
                    ReportPropertyChanging("GUID");
                    _GUID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GUID");
                    OnGUIDChanged();
                }
            }
        }
        private global::System.Guid _GUID;
        partial void OnGUIDChanging(global::System.Guid value);
        partial void OnGUIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FileName
        {
            get
            {
                return _FileName;
            }
            set
            {
                OnFileNameChanging(value);
                ReportPropertyChanging("FileName");
                _FileName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FileName");
                OnFileNameChanged();
            }
        }
        private global::System.String _FileName;
        partial void OnFileNameChanging(global::System.String value);
        partial void OnFileNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] FileBody
        {
            get
            {
                return StructuralObject.GetValidValue(_FileBody);
            }
            set
            {
                OnFileBodyChanging(value);
                ReportPropertyChanging("FileBody");
                _FileBody = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FileBody");
                OnFileBodyChanged();
            }
        }
        private global::System.Byte[] _FileBody;
        partial void OnFileBodyChanging(global::System.Byte[] value);
        partial void OnFileBodyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OrderNum
        {
            get
            {
                return _OrderNum;
            }
            set
            {
                OnOrderNumChanging(value);
                ReportPropertyChanging("OrderNum");
                _OrderNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderNum");
                OnOrderNumChanged();
            }
        }
        private Nullable<global::System.Int32> _OrderNum;
        partial void OnOrderNumChanging(Nullable<global::System.Int32> value);
        partial void OnOrderNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Visible
        {
            get
            {
                return _Visible;
            }
            set
            {
                OnVisibleChanging(value);
                ReportPropertyChanging("Visible");
                _Visible = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Visible");
                OnVisibleChanged();
            }
        }
        private Nullable<global::System.Boolean> _Visible;
        partial void OnVisibleChanging(Nullable<global::System.Boolean> value);
        partial void OnVisibleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> GUID_OfficeFileType
        {
            get
            {
                return _GUID_OfficeFileType;
            }
            set
            {
                OnGUID_OfficeFileTypeChanging(value);
                ReportPropertyChanging("GUID_OfficeFileType");
                _GUID_OfficeFileType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GUID_OfficeFileType");
                OnGUID_OfficeFileTypeChanged();
            }
        }
        private Nullable<global::System.Guid> _GUID_OfficeFileType;
        partial void OnGUID_OfficeFileTypeChanging(Nullable<global::System.Guid> value);
        partial void OnGUID_OfficeFileTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FileKey
        {
            get
            {
                return _FileKey;
            }
            set
            {
                OnFileKeyChanging(value);
                ReportPropertyChanging("FileKey");
                _FileKey = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FileKey");
                OnFileKeyChanged();
            }
        }
        private global::System.String _FileKey;
        partial void OnFileKeyChanging(global::System.String value);
        partial void OnFileKeyChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OAModel", Name="SS_OfficeFileType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SS_OfficeFileType : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 SS_OfficeFileType 对象。
        /// </summary>
        /// <param name="gUID">GUID 属性的初始值。</param>
        /// <param name="fileTypeKey">FileTypeKey 属性的初始值。</param>
        public static SS_OfficeFileType CreateSS_OfficeFileType(global::System.Guid gUID, global::System.String fileTypeKey)
        {
            SS_OfficeFileType sS_OfficeFileType = new SS_OfficeFileType();
            sS_OfficeFileType.GUID = gUID;
            sS_OfficeFileType.FileTypeKey = fileTypeKey;
            return sS_OfficeFileType;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid GUID
        {
            get
            {
                return _GUID;
            }
            set
            {
                if (_GUID != value)
                {
                    OnGUIDChanging(value);
                    ReportPropertyChanging("GUID");
                    _GUID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GUID");
                    OnGUIDChanged();
                }
            }
        }
        private global::System.Guid _GUID;
        partial void OnGUIDChanging(global::System.Guid value);
        partial void OnGUIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FileTypeKey
        {
            get
            {
                return _FileTypeKey;
            }
            set
            {
                OnFileTypeKeyChanging(value);
                ReportPropertyChanging("FileTypeKey");
                _FileTypeKey = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FileTypeKey");
                OnFileTypeKeyChanged();
            }
        }
        private global::System.String _FileTypeKey;
        partial void OnFileTypeKeyChanging(global::System.String value);
        partial void OnFileTypeKeyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FileTypeName
        {
            get
            {
                return _FileTypeName;
            }
            set
            {
                OnFileTypeNameChanging(value);
                ReportPropertyChanging("FileTypeName");
                _FileTypeName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FileTypeName");
                OnFileTypeNameChanged();
            }
        }
        private global::System.String _FileTypeName;
        partial void OnFileTypeNameChanging(global::System.String value);
        partial void OnFileTypeNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> PGUID
        {
            get
            {
                return _PGUID;
            }
            set
            {
                OnPGUIDChanging(value);
                ReportPropertyChanging("PGUID");
                _PGUID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PGUID");
                OnPGUIDChanged();
            }
        }
        private Nullable<global::System.Guid> _PGUID;
        partial void OnPGUIDChanging(Nullable<global::System.Guid> value);
        partial void OnPGUIDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OAModel", Name="SS_OfficeFileTypeView")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SS_OfficeFileTypeView : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 SS_OfficeFileTypeView 对象。
        /// </summary>
        /// <param name="gUID">GUID 属性的初始值。</param>
        /// <param name="fileTypeKey">FileTypeKey 属性的初始值。</param>
        public static SS_OfficeFileTypeView CreateSS_OfficeFileTypeView(global::System.Guid gUID, global::System.String fileTypeKey)
        {
            SS_OfficeFileTypeView sS_OfficeFileTypeView = new SS_OfficeFileTypeView();
            sS_OfficeFileTypeView.GUID = gUID;
            sS_OfficeFileTypeView.FileTypeKey = fileTypeKey;
            return sS_OfficeFileTypeView;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid GUID
        {
            get
            {
                return _GUID;
            }
            set
            {
                if (_GUID != value)
                {
                    OnGUIDChanging(value);
                    ReportPropertyChanging("GUID");
                    _GUID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GUID");
                    OnGUIDChanged();
                }
            }
        }
        private global::System.Guid _GUID;
        partial void OnGUIDChanging(global::System.Guid value);
        partial void OnGUIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FileTypeKey
        {
            get
            {
                return _FileTypeKey;
            }
            set
            {
                if (_FileTypeKey != value)
                {
                    OnFileTypeKeyChanging(value);
                    ReportPropertyChanging("FileTypeKey");
                    _FileTypeKey = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("FileTypeKey");
                    OnFileTypeKeyChanged();
                }
            }
        }
        private global::System.String _FileTypeKey;
        partial void OnFileTypeKeyChanging(global::System.String value);
        partial void OnFileTypeKeyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FileTypeName
        {
            get
            {
                return _FileTypeName;
            }
            set
            {
                OnFileTypeNameChanging(value);
                ReportPropertyChanging("FileTypeName");
                _FileTypeName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FileTypeName");
                OnFileTypeNameChanged();
            }
        }
        private global::System.String _FileTypeName;
        partial void OnFileTypeNameChanging(global::System.String value);
        partial void OnFileTypeNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> PGUID
        {
            get
            {
                return _PGUID;
            }
            set
            {
                OnPGUIDChanging(value);
                ReportPropertyChanging("PGUID");
                _PGUID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PGUID");
                OnPGUIDChanged();
            }
        }
        private Nullable<global::System.Guid> _PGUID;
        partial void OnPGUIDChanging(Nullable<global::System.Guid> value);
        partial void OnPGUIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PKey
        {
            get
            {
                return _PKey;
            }
            set
            {
                OnPKeyChanging(value);
                ReportPropertyChanging("PKey");
                _PKey = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PKey");
                OnPKeyChanged();
            }
        }
        private global::System.String _PKey;
        partial void OnPKeyChanging(global::System.String value);
        partial void OnPKeyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PName
        {
            get
            {
                return _PName;
            }
            set
            {
                OnPNameChanging(value);
                ReportPropertyChanging("PName");
                _PName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PName");
                OnPNameChanged();
            }
        }
        private global::System.String _PName;
        partial void OnPNameChanging(global::System.String value);
        partial void OnPNameChanged();

        #endregion
    
    }

    #endregion
    
}
